name: GitHub Action for Zadanie 1
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: [ v* ]

jobs:
  build-push-images:
    # The type of runner that the job will run on
    name: Budowa i publikacja obrazow na repozytorium
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #Skonfigurowanie dockera + buildx
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      #Instalacja QEMU
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      #Logowanie do Dockerhuba
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Login to GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.PASS}}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            damianflis1999/fibcalc
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      #Zbudowanie i wypchniecie obrazu na Dockerhuba
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64 
          context: ./
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=docker.io/damianflis1999/fibcalc:cache
          cache-to: type=registry,ref=docker.io/damianflis1999/fibcalc:cache,mode=max
